var express = require('express')
var authMiddleware = require('../middlewares/auth')
var memberRouter = express.Router()
const MemberController = require('../controllers/memberController')
memberRouter.route('/login')
    .post(MemberController.login)
memberRouter.route('/signup')
    .post(MemberController.signUp)
memberRouter.route('/:id/change-password')
    .put(authMiddleware, MemberController.changePassword)
memberRouter.route('/:id')
    .put(authMiddleware, MemberController.update)
module.exports = memberRouter
