var express = require('express')
var {authMiddleware, adminCheck} = require('../middlewares/auth')
var memberRouter = express.Router()
const MemberController = require('../controllers/memberController')
memberRouter.route('/login')
    .post(MemberController.login)
memberRouter.route('/signup')
    .post(MemberController.signUp)
memberRouter.route('/collector')
    .get(authMiddleware, adminCheck, MemberController.getAllUsers)
memberRouter.route('/:id/change-password')
    .put(authMiddleware, MemberController.changePassword)
memberRouter.route('/:id/comments')
    .get(authMiddleware, MemberController.getUserComments)
memberRouter.route('/:id')
    .put(authMiddleware, MemberController.update)
module.exports = memberRouter
